### PR TITLE
Adding 'priority' route option

### PR DESCRIPTION
**Pull request by boosis**
Simply adding 'priority' route config to the annotations.

### CODE REVIEW

**Comment by alex-oleshkevich** [comment]
1. you did not follow a code style;
2. revert array notation back to "array()". A minimal supported PHP version is 5.3 (same as ZF2 has) -- [] was introduced in 5.4.

So before I merge PR you have to:
0. refactor code to meet standards;
1. add a new feature (priority option) without unnecessary changes in other files;
2. update unit tests.

**Comment by alex-oleshkevich** [comment]
consider pushing these changes also to https://github.com/alex-oleshkevich/zf-annotations
i' m going to deprecate this module (zf2-annotated-router) in favor of  zf-annotations.

**Comment by boosis** [comment]
Ah, my ide automatically formats the code when I save a file. I'll fix them asap.
Which file has unnecessary changes?

**Comment by alex-oleshkevich** [comment]
a). correct package name in `composer.json`. `composer.phar` uses it as dependency name;
b). unit tests fails (you did not update asserts with new property "priority".

**Comment by boosis** [comment]
Can you cancel this pull request please?

**Comment by alex-oleshkevich** [comment]
ok

On Tue, Feb 17, 2015 at 9:56 AM, Bill Yildirim <notifications@github.com>
wrote:

> Can you cancel this pull request please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alex-oleshkevich/zf2-annotated-router/pull/2#issuecomment-74625109>
> .
>



-- 
Sincerely,
Alex Oleshkevich

skype: alex.oleshkevich
email:alex.oleshkevich@gmail.com

**Pull request closed without merging**
